name: Ddeploy image to ghcr

on:
  push:
    tags:        
      - '*'

jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build Image'
        run: |
          docker build . --tag ghcr.io/smallru8/frr-grpc:${{  github.ref_name }}-ubuntu
          docker push ghcr.io/smallru8/frr-grpc:${{  github.ref_name }}-ubuntu
          